### ISSUE TITLE
Client Side Crash

### ISSUE THREAD

**Issue by Dev0Louis** [samolego/GolfIV#69]
There is a Client side crash.
```
java.lang.ClassCastException: class net.minecraft.client.network.ClientPlayerEntity cannot be cast to class org.samo_lego.golfiv.casts.Golfer (net.minecraft.client.network.ClientPlayerEntity and org.samo_lego.golfiv.casts.Golfer are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @5622fdf)
	at org.samo_lego.golfiv.event.combat.InventoryHitCheck.interact(InventoryHitCheck.java:30)
	at net.fabricmc.fabric.api.event.player.UseEntityCallback.lambda$static$0(UseEntityCallback.java:57)
	at net.minecraft.client.MinecraftClient.handler$zbo000$fabric-events-interaction-v0$injectUseEntityCallback(MinecraftClient.java:3123)
	at net.minecraft.client.MinecraftClient.doItemUse(MinecraftClient.java:1782)
	at net.minecraft.client.MinecraftClient.handleInputEvents(MinecraftClient.java:2061)
	at net.minecraft.client.MinecraftClient.tick(MinecraftClient.java:1880)
	at net.minecraft.client.MinecraftClient.render(MinecraftClient.java:1180)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient.java:801)
	at net.minecraft.client.main.Main.main(Main.java:237)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86)
```
I will try to fix it 👯

**Comment by Dev0Louis** [comment]
# #70(Fixed it)
